#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE "$POSTGRES_LIZMAP_USER" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$POSTGRES_LIZMAP_PASSWORD';
	CREATE DATABASE "$POSTGRES_LIZMAP_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_LIZMAP_DB" TO "$POSTGRES_LIZMAP_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_LIZMAP_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS "postgis";
        CREATE EXTENSION IF NOT EXISTS "postgis_raster";
        CREATE SCHEMA "lizmap" AUTHORIZATION "$POSTGRES_LIZMAP_USER";
EOSQL
