#!/usr/bin/env bash

set -e

export LIZMAP_DIR=${LIZMAP_DIR:-$(pwd)/lizmap}
export LIZMAP_USER_ID=${LIZMAP_USER:-$(id -u)}
export LIZMAP_USER_GID=${LIZMAP_GID:-$(id -g)}

docker-compose rm || true
docker-compose up

